# Generated by Django 2.0.7 on 2018-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('assunto', models.CharField(max_length=500)),
            ],
        ),
    ]
